### ISSUE TITLE
可不可以适配一下北邮人？

### ISSUE THREAD

**Issue by patialo** [mantou568/pre-dessert-sites#21]
请问可以适配一下byr吗，谢谢

**Comment by jiezaizone** [comment]
> 请问可以适配一下byr吗，谢谢

将站点的地址以及种子页面的源代码导出来保存打包一份发出来我看看能不能给适配个，浏览器右键查看源代码，

**Comment by patialo** [comment]
您看看行不，我把地址也放在压缩包里了，完成后我就删除这条 @jiezaizone 

[byr.zip](https://github.com/mantou568/pre-dessert-sites/files/15289788/byr.zip)

**Comment by jiezaizone** [comment]
> 您看看行不，我把地址也放在压缩包里了，完成后close一下，我把这条评论删除 @jiezaizone
> 
> [byr.zip](https://github.com/mantou568/pre-dessert-sites/files/15289788/byr.zip)

简单适配了一下，没有号没得测试，你自己更新测试一下吧

**Comment by patialo** [comment]
> 简单适配了一下，没有号没得测试，你自己更新测试一下吧

目前用下来可以了，谢谢
