### ISSUE TITLE
新站CD file求适配

### ISSUE THREAD

**Issue by sunld666** [mantou568/pre-dessert-sites#22]
https://pt.cdfile.org/

**Comment by zjjxwhh** [comment]
https://github.com/mantou568/pre-dessert-sites/commit/c523a7259fedc4b7e166da28ff13f0f896195107 适配了，测试一下

**Comment by sunld666** [comment]
> [c523a72](https://github.com/mantou568/pre-dessert-sites/commit/c523a7259fedc4b7e166da28ff13f0f896195107) 适配了，测试一下

感谢大佬适配
